# TODO move assemble step to main compile job
platform: linux

inputs:
  # TODO get libraries from artifact repository
  - name: source-code
  - name: .gradle
  - name: .m2

outputs:
  - name: shared-jar
  - name: .gradle
  - name: .m2
  - name: application-jar
  - name: api-jar

caches:
  - path: ./gradle/
  - path: ./m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step d: Assemble libraries"

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn package:jar"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew assemble"
      fi

      echo $targetCommand
      eval "$targetCommand"
