platform: linux

inputs:
  # TODO get libraries from artifact repository
  - name: source-code

outputs:
  - name: shared-jar
  - name: application-jar
  - name: api-jar

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step d: Assemble libraries"

      # TODO get libraries from artifact repository

      ls -lah {..,.}

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn package:jar"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew assemble"
      fi

      echo $targetCommand
      # eval "$targetCommand"

      echo "--------------------------------------------------------------"
      touch {shared-jar,application-jar,api-jar}/assemble.jar


      echo "--------------------------------------------------------------"
      touch {.,build-logic,api,app,lib}/build/assemble.md

      echo "--------------------------------------------------------------"
      find . -name '*.md'
      find . -name '*.jar'
