platform: linux

inputs:
  - name: source-code
  - name: .gradle
  - name: .m2

outputs:
  - name: source-code
  - name: .gradle
  - name: .m2

caches:
  - path: ./gradle/
  - path: ./m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 2b: Mutation Test"


      export ROOT_FOLDER=$(pwd)/..
      export GRADLE_USER_HOME="${ROOT_FOLDER}/.gradle"
      export M2_HOME=${ROOT_FOLDER}/.m2
      export M2_LOCAL_REPO="${ROOT_FOLDER}/.m2"

      echo "HOME set to " ${HOME}

      echo "GRADLE_USER_HOME set to  " ${GRADLE_USER_HOME}
      # mkdir -p ${GRADLE_USER_HOME}

      echo "M2_HOME set to  " ${M2_HOME}
      # mkdir -p ${M2_HOME}


      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn mutation-test:run"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew  pitest"
      fi

      echo $targetCommand
      eval "$targetCommand"

      # echo "--------------------------------------------------------------"
      # touch {.,build-logic,api,app,lib}/build/pitest.md

      # echo "--------------------------------------------------------------"
      # find . -name '*.md'
