platform: linux

inputs:
  - name: source-code

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 2b: Mutation Test"

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn mutation-test:run"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew  pitest"
      fi

      echo $targetCommand
      # eval "$targetCommand"
