platform: linux

inputs:
  - name: source-code

  - name: build-compiled
    path: build-logic/build
  - name: build
  - name: api-build
    path: api/build
  - name: app-build
    path: app/build
  - name: lib-build
    path: lib/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step d: Publish Artifacts"

      ls -lahR build-compiled
      ls -lahR build
      ls -lahR api-build
      ls -lahR app-build
      ls -lahR lib-build

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn package:jar"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew assemble"
      fi

      echo $targetCommand
      # eval "$targetCommand"
