platform: linux

inputs:
  - name: source-code

outputs:
  - name: source-code

caches:
  - path: ./gradle/
  - path: ./m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 3a: Static Analysis - Checkstyle"

      ls -lah {.,build-logic,api,app,lib}/{.,build}

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn checkstyle:check"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew checkstyleMain checkstyleTest"
      fi

      echo $targetCommand
      # eval "$targetCommand"

      echo "--------------------------------------------------------------"
      touch {.,build-logic,api,app,lib}/build/checkstyle.md

      echo "--------------------------------------------------------------"
      find . -name '*.md'
