platform: linux

inputs:
  - name: source-code

  # From compile
  - name: build-compiled
    path: build-logic/build
  - name: build-output
  - name: api-build
    path: api/build
  - name: app-build
    path: app/build
  - name: lib-build
    path: lib/build

outputs:
  - name: build-compiled
    path: build-logic/build
  - name: build-output
  - name: api-build
    path: api/build
  - name: app-build
    path: app/build
  - name: lib-build
    path: lib/build

caches:
  - path: ./gradle/
  - path: ./m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 3a: Static Analysis - Checkstyle"

      ls -lah {.,build-logic,api,app,lib}/{.,build}

      # ls -lah
      # ls -lahR
      # ls -lah build-compiled
      # ls -lah build-output
      # ls -lah api-build
      # ls -lah app-build
      # ls -lah lib-build

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn checkstyle:check"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew checkstyleMain checkstyleTest"
      fi

      echo $targetCommand
      # eval "$targetCommand"

      echo "--------------------------------------------------------------"
      touch {.,build-logic,api,app,lib}/build/pmd.md
      # touch build-output/checkstyle.md
      # touch build-compiled/checkstyle.md
      # touch api-build/checkstyle.md
      # touch app-build/checkstyle.md
      # touch lib-build/checkstyle.md

      # echo "--------------------------------------------------------------"
      # ls -lahR build-compiled
      # ls -lahR build-output
      # ls -lahR api-build
      # ls -lahR app-build
      # ls -lahR lib-build

      find . -name '*.md'
