platform: linux

inputs:
  - name: source-code
  - name: .gradle
  - name: .m2

outputs:
  - name: source-code
  - name: .gradle
  - name: .m2

caches:
  - path: .gradle/
  - path: .m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 3b: Static Analysis - PMD"

      ls -lah {.,build-logic,api,app,lib}/{.,build}
      # ls -lahR build-compiled
      # ls -lahR build-output
      # ls -lahR api-build
      # ls -lahR app-build
      # ls -lahR lib-build

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn pmd:check"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew pmdMain pmdTest"
      fi

      echo $targetCommand
      # eval "$targetCommand"

      echo "--------------------------------------------------------------"
      touch {.,build-logic,api,app,lib}/build/pmd.md

      # touch build-output/pmd.md
      # touch build-compiled/pmd.md
      # touch api-build/pmd.md
      # touch app-build/pmd.md
      # touch lib-build/pmd.md

      echo "--------------------------------------------------------------"
      # ls -lahR build-compiled
      # ls -lahR build-output
      # ls -lahR api-build
      # ls -lahR app-build
      # ls -lahR lib-build

      find . -name '*.md'
