platform: linux

inputs:
  - name: source-code

outputs:
  - name: source-code

caches:
  - path: ./gradle/
  - path: ./m2/
  - path: build-logic/build

run:
  dir: source-code
  path: sh
  args:
    - -cx
    - |
      echo "Step 2a: Unit Tests & Coverage"

      ls -lah {.,build-logic,api,app,lib}/{.,build}

      java -version

      pwd
      # ls -lah

      # Detect build tool and run lifecycle
      if [ -f "pom.xml" ]; then
        targetCommand="mvn verify coverage:report"
      elif [ -f "build.gradle" ]; then
        targetCommand="./gradlew check jacocoTestReport"
      fi

      echo $targetCommand
      # eval "$targetCommand"

      echo "--------------------------------------------------------------"
      touch {.,build-logic,api,app,lib}/build/unit-test.md

      echo "--------------------------------------------------------------"
      find . -name '*.md'
