
##### Application
server:
  port: ${port:8100}
  servlet:
    context-path: /api/v1



##### Spring
spring:
  application:
    name: airport-service

  profiles:
    active:  ${active_profiles:local}

  main:
    lazy-initialization: true

  config:
    import: "optional:configserver:http://localhost:8888"

  ## --- DataSource ---
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Datasource is defined in a profile specific application-<profile>.yaml
  datasource:
    driver-class-name: ${datasource.driver.classname}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}


#  jpa:
#    hibernate:
    # none, validate, update, create, create-drop
#      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # End of what should be in local profile (this is not prod compliant)





##### Logging configuration #####
logging:
  level:
    root: INFO


#################

partner-services:
  services:
    - name: service1
      hostname: host1.some.domain
      health-endpoint: /health

    - name: service2
      hostname: host2.some.domain

# TODO this should be in a local profile
datasource:
  username: sa
  password: sa
  # schema: something
  url: jdbc:h3:mem:testdb;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  driver:
    classname: org.h2.Driver
