
##### Application
server:
  port: ${port:8100}
  servlet:
    context-path: /api/v1
  error:
    include-binding-errors: always



##### Spring
spring:
  application:
    name: airport-service

  jackson:
    default-property-inclusion: NON_NULL

  profiles:
    active:  ${active_profiles:local}

  main:
    lazy-initialization: true

#  mvc:
     # hides validation errors
#    problemdetails:
#      enabled: true

  config:
    import: "optional:configserver:http://localhost:8888"

  ## --- DataSource ---
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # Datasource is defined in a profile specific application-<profile>.yaml
  datasource:
    driver-class-name: ${datasource.driver.classname}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}


#  jpa:
#    hibernate:
    # none, validate, update, create, create-drop
#      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

  # End of what should be in local profile (this is not prod compliant)





##### Logging configuration #####
logging:
  level:
    root: WARN


#################

partner-services:
  services:
    - name: service1
      hostname: host1.some.domain
      health-endpoint: /health

    - name: service2
      hostname: host2.some.domain

# TODO this should be in a local profile
datasource:
  username: sa
  password: sa
  # schema: something
  url: jdbc:h3:mem:testdb;
  driver:
    classname: org.h2.Driver


management:

  # Auto-configuation of liveness/readiness probes
  health:
    probes:
      enabled: true

  endpoints:
    web:
      base-path: /actuator
      # cors:
      #   allowed-origins: "http://example.com"
      #   allowed-methods: "GET,POST"
      exposure:
        include: info,health,liquibase

  endpoint:
    # SRE Health (liveness, readiness) for integration with kubernetes
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true
      show-details: always
      # status:
      #   order: fatal,down,out-of-service,degraded,unknown,up
      #   http-mapping:
      #     degraded: 242
      #     unknown: 242
      #     fatal: 503
      #     down: 503
      #     out-of-service: 503

    liquibase:
      access: UNRESTRICTED

    metrics:
      access: UNRESTRICTED

    prometheus:
      access: UNRESTRICTED


  # ---------- Feature specific configurations ----------
  # --- Metrics (Prometheus) ---
  prometheus:
    metrics:
      export:
        enabled: true


  # --- Informaion about the application ---
  # {"git":{"commit":{"time":"2019-11-23T23:41:52Z","id":"5b27927"},"branch":"development"}}
  info:
    app:
      name: ${spring.application.name}
      version: ${project.version}
      java:
        version: ${java.version}
        source: ${java.version}
        target: ${java.version}
    env:
      enabled: true
    java:
      enabled: true
    git:
      mode: full



