services:

  artifact-repository:
    image: dzikoysk/reposilite
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      # REPOSOLITE_OPTS: --local-configuration=/app/configuration.cdn --token admin:secret
      # REPOSILITE_OPTS: --port 8080 --token admin:secret
      # REPOSILITE_OPTS: --port 8080
      REPOSILITE_OPTS: --token admin:secret
    volumes:
      - reposilite-data:/app/data

  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database
      POSTGRES_HOST_AUTH_METHOD: trust #for healthcheck
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concourse_user -d concourse"]
      interval: 3s
      timeout: 3s
      retries: 5

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    cgroup: host
    depends_on:
      concourse-db:
        condition: service_healthy
    ports: ["8082:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8082
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_CLUSTER_NAME: tutorial
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
      CONCOURSE_WORKER_RUNTIME: "containerd"
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_ENABLE_RESOURCE_CAUSALITY: "true"

volumes:
  pg_data:
  reposilite-data:

