# Concourse CI Pipeline Definition
# Refactored to use configuration variables for sensitive data and environment-specific URIs.

# the following vars must be specified:
#
#   ((git_uri))                 URI of the git repository
#   ((git_repository))          The name of the git repository, owned by git_owner
#   ((git_owner))               git account name
#   ((git_username))            username of the git repository
#   ((git_password))            password for the git repository
#   ((github_access_token))     fine-grained git access token

meta:
  icons:
    - &java-icon language-java
    - &git-icon github

resources:
  - name: source-code
    type: git
    icon: *git-icon
    source:
      uri: ((git_uri))
      username: ((git_username))
      password: ((git_password))
      branch: ((git_branch))

  - name: java-builder-image
    type: registry-image
    icon: *java-icon
    source:
      repository: gradle
      tag: jdk26-ubi
      # username: ((docker.user))
      # password: ((docker.password))

  # TODO Create a repository for the standard pipeline tasks
  - name: pipeline-tasks
    type: git
    icon: *git-icon
    source:
      uri: ((pipeline_uri))
      username: ((pipeline_username))
      password: ((pipeline_password))
      branch: ((pipeline_branch))

groups:
  - name: all
    jobs:
      - "*"
  - name: build
    jobs:
      - compile
  - name: static-analysis
    jobs:
      - static-*
  - name: dynamic-analysis
    jobs:
      - unit-test
      - mutation-test
  - name: package
    jobs:
      - assemble
      - create-docker-image
  - name: publish
    jobs:
      - publish

  # TODO Dummy groups for the moment
  - name: deploy-dev
    jobs:
      - publish
  - name: deploy-qa
    jobs:
      - publish
  - name: deploy-staging
    jobs:
      - publish
  - name: deploy-prod
    jobs:
      - publish

jobs:
  ## Compile and Test
  - name: compile
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
      - task: compile
        image: java-builder-image
        timeout: 15m
        config:
          platform: linux
          # image_resource: &compile_image
          #   type: registry-image
          #   source:
          #     repository: gradle
          #     tag: jdk26-ubi
          inputs:
            - name: source-code
          outputs:
            - name: build-compiled
              path: build-logic/build
            - name: build
            - name: api-build
              path: api/build
            - name: app-build
              path: app/build
            - name: lib-build
              path: lib/build
          caches:
            - path: ./gradle/
            - path: ./m2/
            - path: build-logic/build
          run:
            dir: source-code
            path: sh
            args:
              - -cx
              - |
                echo "Step 1: Compilation (Blocking)"
                pwd
                # ls -lah
                # ls --help
                # ls -lR source-code/pipeline/provider
                # cd source-code
                # ls -lah
                # ls -lR

                chmod +x ./gradlew

                java -version

                export ROOT_FOLDER=$( pwd )
                export GRADLE_USER_HOME="${ROOT_FOLDER}/.gradle"
                export M2_HOME=${ROOT_FOLDER}/.m2
                export M2_LOCAL_REPO="${ROOT_FOLDER}/.m2"

                echo "HOME set to " ${HOME}

                echo "GRADLE_USER_HOME set to  " ${GRADLE_USER_HOME}
                mkdir -p ${GRADLE_USER_HOME}

                echo "M2_HOME set to  " ${M2_HOME}
                mkdir -p ${M2_HOME}

                ls -lah

                # Detect build tool and run lifecycle
                if [ -f "pom.xml" ]; then
                  buildCommand="mvn clean compile test-compile"
                elif [ -f "build.gradle" ]; then
                  buildCommand="./gradlew clean classes testClasses"
                fi

                echo $buildCommand
                eval "$buildCommand"

                touch build/readme
                touch build-compiled/readme
                touch api-build/readme
                touch app-build/readme
                touch lib-build/readme

                cp -R /build build
                cp -R /build-logic/build build-compiled
                cp -R api/build api-build
                cp -R app/build app-build
                cp -R lib/build lib-build

                ls -lah $M2_HOME
                ls -lah $GRADLE_USER_HOME

                ls -lahR build-compiled
                ls -lahR build
                ls -lahR api-build
                ls -lahR app-build
                ls -lahR lib-build

  ####
  ## Dynamic analysis
  - name: unit-test
    plan:
      - get: java-builder-image
      - get: pipeline-tasks
      - get: source-code
        trigger: true
        passed: [compile]
      - task: unit-test
        file: pipeline-tasks/pipeline/provider/concourse/tasks/unit-test.yml
        image: java-builder-image
        timeout: 5m

  - name: mutation-test
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
            passed: [compile]
      - task: mutation-test
        image: java-builder-image
        timeout: 5m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/mutation-test.yml

  ## Static analysis

  - name: static-analysis-checkstyle
    plan:
      - get: java-builder-image
      - get: pipeline-tasks
      - get: source-code
        trigger: true
        passed: [compile]
      - task: checkstyle
        image: java-builder-image
        timeout: 10m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/static-analysis-checkstyle.yml

  - name: static-analysis-pmd
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
            passed: [compile]
      - task: pmd
        image: java-builder-image
        timeout: 10m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/static-analysis-pmd.yml

  ## Assemble and publish
  ## TODO calculate the new semver
  - name: assemble
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
            passed:
              [
                unit-test,
                mutation-test,
                static-analysis-pmd,
                static-analysis-checkstyle,
              ]
      ## TODO output all the libraries (jar files)
      - task: assemble
        image: java-builder-image
        timeout: 5m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/assemble.yml

  ## TODO vulnerability scan with Trivy

  ## publish

  - name: create-docker-image
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
            passed: [assemble]
      ## TODO output is the docker file
      - task: docker-image
        image: java-builder-image
        timeout: 5m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/create-docker-image.yml

      - task: vulnerability-scan
        image: java-builder-image
        timeout: 5m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/vulnerability-scan.yml

  ## TODO vulnerability scan with Trivy

  - name: publish
    plan:
      - in_parallel:
          - get: java-builder-image
          - get: pipeline-tasks
          - get: source-code
            trigger: true
            passed: [assemble, create-docker-image]
      ## TODO Input are the jars and docker file.
      - task: publish
        image: java-builder-image
        timeout: 5m
        file: pipeline-tasks/pipeline/provider/concourse/tasks/publish.yml
