/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.app;

import static com.example.app.MessageUtils.getMessage;
import static com.example.utilities.StringUtils.join;
import static com.example.utilities.StringUtils.split;

import com.example.list.LinkedList;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
